AWSTemplateFormatVersion: '2010-09-09'
Description: VCIS API Gateway

Transform: [VcisCommonTagsMacro]

Parameters:
  Env:
    Type: String
    Description: Environment in which resources should be deployed
    AllowedValues:
      - poc
      - dev
      - it
      - prod
    ConstraintDescription: Must be either poc, dev, it or prod

  ProjectModuleTag:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Project Module Tag SSM Param Name. Default is '/vcis/{Env}/infra/tags/project-module-value-capture-industry-system'

  RestApiName:
    Type: String
    Description: 'The API Name (eg: vcis-pod-credit-exemption-balance)'

  RestApiDescription:
    Type: String
    Description: Rest API Description

  StageName:
    Type: String
    Description: The name of the API Stage. Default is 'release' stage
    Default: 'release'

  RestApiCustomDomainName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Rest API Custom Domain Name. Default value is 'api.pod-np.its-plus.com' (NonProd) and 'api.pod.its-plus.com' (Prod)

  LambdaAuthorizerStackName:
    Type: String
    Description: Stack that exports Lambda Authorizer ARN.

  MinimumCompressionSize:
    Type: Number
    Default: 0
    Description: 'Compression or decompression is not applied on the payload if the payload size is smaller than this value. Setting it to zero allows compression for any payload size.'

  CustomTags:
    Type: String
    Description: "Custom tags to apply on template"
    Default: ''

Mappings:
  EnvStageVarMapping:
    poc:
      EnvStageVar: 'DEV'
    dev:
      EnvStageVar: 'DEV'
    it:
      EnvStageVar: 'TEST'
    prod:
      EnvStageVar: 'PROD'

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${RestApiName}-${Env}'
      Description: !Ref RestApiDescription
      ApiKeySourceType: HEADER
      MinimumCompressionSize: !Ref MinimumCompressionSize
      EndpointConfiguration:
        Types:
          - EDGE

    ## Lambda Authorizer
  ApiGatewayLambdaAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    DependsOn: RestApi
    Properties:
      Name: !Sub 'vcis-pod-ping-authorizer-${Env}'
      Type: 'REQUEST'
      AuthorizerResultTtlInSeconds: 0
      AuthorizerUri: !Join
        - ''
        - - 'arn:aws:apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - Fn::ImportValue: !Sub "${LambdaAuthorizerStackName}-PodPingAuthorizer"
          - '/invocations'
      IdentitySource: 'method.request.header.Authorization'
      RestApiId: !Ref RestApi

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
    - PodPath
    - PodparticipantPath
    - PodparticipantdeliveryPath
    - PodparticipantdeliverybulkPath
    - PodparticipantdeliverybulkcsvPath
    - PodparticipantdeliverybulkcsvbulkIdPath
    - PodparticipantdeliverybulkxlsxPath
    - PodparticipantdeliverybulkxlsxbulkIdPath
    - PodparticipantdeliverycsvPath
    - PodparticipantdeliverycsvfilenamePath
    - PodparticipantdeliveryqbulkPath
    - PodparticipantdeliverysumPath
    - PodparticipantdeliveryxlsxPath
    - PodparticipantdeliveryxlsxfilenamePath
    - PodparticipantdeliveryidPath
    - PodparticipantdeliveryidcancelPath
    - PodparticipantdeliveryOptionsMethod
    - PodparticipantdeliverybulkOptionsMethod
    - PodparticipantdeliverybulkxlsxbulkIdOptionsMethod
    - PodparticipantdeliverysumOptionsMethod
    - PodparticipantdeliveryxlsxfilenameOptionsMethod
    - PodparticipantdeliveryidOptionsMethod
    - PodparticipantdeliveryidcancelOptionsMethod
    Properties:
      Description: API Deployment
      RestApiId: !Ref RestApi

  Stage:
    Type: AWS::ApiGateway::Stage
    DependsOn: Deployment
    Properties:
      RestApiId: !Ref RestApi
      DeploymentId: !Ref Deployment
      StageName: !Ref StageName
      Variables:
        environment: !FindInMap [EnvStageVarMapping, !Ref Env, EnvStageVar]

  ApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: Stage
    Properties:
      DomainName: !Ref RestApiCustomDomainName
      BasePath: !Sub '${RestApiName}-${Env}'
      RestApiId: !Ref RestApi
      Stage: !Ref Stage

  PodPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: "pod"
      RestApiId: !Ref RestApi

  PodparticipantPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodPath
      PathPart: "participant"
      RestApiId: !Ref RestApi

  PodparticipantdeliveryPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantPath
      PathPart: "delivery"
      RestApiId: !Ref RestApi

  PodparticipantdeliveryOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref PodparticipantdeliveryPath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  PodparticipantdeliverybulkPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliveryPath
      PathPart: "bulk"
      RestApiId: !Ref RestApi

  PodparticipantdeliverybulkOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref PodparticipantdeliverybulkPath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  PodparticipantdeliverybulkcsvPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliverybulkPath
      PathPart: "csv"
      RestApiId: !Ref RestApi

  PodparticipantdeliverybulkcsvbulkIdPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliverybulkcsvPath
      PathPart: "{bulkId}"
      RestApiId: !Ref RestApi

  PodparticipantdeliverybulkxlsxPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliverybulkPath
      PathPart: "xlsx"
      RestApiId: !Ref RestApi

  PodparticipantdeliverybulkxlsxbulkIdPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliverybulkxlsxPath
      PathPart: "{bulkId}"
      RestApiId: !Ref RestApi

  PodparticipantdeliverybulkxlsxbulkIdOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref PodparticipantdeliverybulkxlsxbulkIdPath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  PodparticipantdeliverycsvPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliveryPath
      PathPart: "csv"
      RestApiId: !Ref RestApi

  PodparticipantdeliverycsvfilenamePath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliverycsvPath
      PathPart: "{filename}"
      RestApiId: !Ref RestApi

  PodparticipantdeliveryqbulkPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliveryPath
      PathPart: "qbulk"
      RestApiId: !Ref RestApi

  PodparticipantdeliverysumPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliveryPath
      PathPart: "sum"
      RestApiId: !Ref RestApi

  PodparticipantdeliverysumOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref PodparticipantdeliverysumPath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  PodparticipantdeliveryxlsxPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliveryPath
      PathPart: "xlsx"
      RestApiId: !Ref RestApi

  PodparticipantdeliveryxlsxfilenamePath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliveryxlsxPath
      PathPart: "{filename}"
      RestApiId: !Ref RestApi

  PodparticipantdeliveryxlsxfilenameOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref PodparticipantdeliveryxlsxfilenamePath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  PodparticipantdeliveryidPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliveryPath
      PathPart: "{id}"
      RestApiId: !Ref RestApi

  PodparticipantdeliveryidOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref PodparticipantdeliveryidPath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  PodparticipantdeliveryidcancelPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref PodparticipantdeliveryidPath
      PathPart: "cancel"
      RestApiId: !Ref RestApi

  PodparticipantdeliveryidcancelOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref PodparticipantdeliveryidcancelPath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false

Outputs:
  Endpoint:
    Description: Rest Api Endpoint URL
    Value: !Sub 'https://${RestApiName}-${Env}.execute-api.${AWS::Region}.amazonaws.com'

  RestApiGatewayId:
    Description: ApiGatewayId
    Value: !Ref RestApi
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayId'

  RootResourceId:
    Description: RootResourceId
    Value: !GetAtt RestApi.RootResourceId
    Export:
      Name: !Sub '${AWS::StackName}-RootResourceId'

  LambdaAuthorizerId:
    Description: LambdaAuthorizerId
    Value: !Ref ApiGatewayLambdaAuthorizer
    Export:
      Name: !Sub '${AWS::StackName}-LambdaAuthorizerId'

  PodPath:
    Value: !Ref PodPath
    Export:
      Name: !Sub '${AWS::StackName}-PodPath'
  PodparticipantPath:
    Value: !Ref PodparticipantPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantPath'
  PodparticipantdeliveryPath:
    Value: !Ref PodparticipantdeliveryPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliveryPath'
  PodparticipantdeliverybulkPath:
    Value: !Ref PodparticipantdeliverybulkPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliverybulkPath'
  PodparticipantdeliverybulkcsvPath:
    Value: !Ref PodparticipantdeliverybulkcsvPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliverybulkcsvPath'
  PodparticipantdeliverybulkcsvbulkIdPath:
    Value: !Ref PodparticipantdeliverybulkcsvbulkIdPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliverybulkcsvbulkIdPath'
  PodparticipantdeliverybulkxlsxPath:
    Value: !Ref PodparticipantdeliverybulkxlsxPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliverybulkxlsxPath'
  PodparticipantdeliverybulkxlsxbulkIdPath:
    Value: !Ref PodparticipantdeliverybulkxlsxbulkIdPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliverybulkxlsxbulkIdPath'
  PodparticipantdeliverycsvPath:
    Value: !Ref PodparticipantdeliverycsvPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliverycsvPath'
  PodparticipantdeliverycsvfilenamePath:
    Value: !Ref PodparticipantdeliverycsvfilenamePath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliverycsvfilenamePath'
  PodparticipantdeliveryqbulkPath:
    Value: !Ref PodparticipantdeliveryqbulkPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliveryqbulkPath'
  PodparticipantdeliverysumPath:
    Value: !Ref PodparticipantdeliverysumPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliverysumPath'
  PodparticipantdeliveryxlsxPath:
    Value: !Ref PodparticipantdeliveryxlsxPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliveryxlsxPath'
  PodparticipantdeliveryxlsxfilenamePath:
    Value: !Ref PodparticipantdeliveryxlsxfilenamePath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliveryxlsxfilenamePath'
  PodparticipantdeliveryidPath:
    Value: !Ref PodparticipantdeliveryidPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliveryidPath'
  PodparticipantdeliveryidcancelPath:
    Value: !Ref PodparticipantdeliveryidcancelPath
    Export:
      Name: !Sub '${AWS::StackName}-PodparticipantdeliveryidcancelPath'
