AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS CloudFormation Template Continuous Delivery: This template
  builds an AWS CodePipeline pipeline that implements a continuous delivery release
  process for AWS CloudFormation stacks. Submit a CloudFormation source artifact
  to an Amazon S3 location before building the pipeline. The pipeline uses the
  artifact to automatically create stacks and change sets.
Transform: [VcisCommonTagsMacro]

Parameters:
  WorkloadName:
    Description: 'A name for the workload used in SSM Parameter Store.'
    Type: String
  Env:
    Description: >-
      A value used to describe the environment you will deploy to. This value will be used to get values
      from SSM Parameter Store. Keys in Parameter store should begin with: /vcis/environment.
    Type: String
    AllowedValues:
      - prod
      - dev
      - it
      - poc
      # non-prod should be used only for account level infra resources (for non-prod account)
      - non-prod
    ConstraintDescription: Must be a prod, dev, it or poc.
  ProjectModuleTag:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Project Module Tag Value
  TemplateFileName:
    Description: >-
      The value is the name of the CloudFormation template to deploy.
    Type: String
  ConfigPath:
    Description: >-
      The value is the path to the CloudFormation parameter file to deploy.
    Type: String


  # Params with Default values
  WorkLoadAccountLevelInputParamsStackName:
    Description: >-
      The name of the stack name that is exporting the pipeline workload inputs
    Type: String

  S3SourceKey:
    Description: >-
      File name that is the repository artifact.
    Type: String
    Default: 'vcis-cloudformation-templates'

  InfraDeploymentApprovalSlackNotifierStackName:
    Description: >-
      The name of the stack that is exporting the Infra Operational Slack Notifier SNS Topic
    Type: 'String'
    Default: 'vcis-prod-infra-approvals-slack-notifier'

  CfnStackEraserStackName:
    Type: String
    Description: 'Cfn stack eraser custom resource stack'
    Default: 'vcis-cloudformation-custom-resources'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "CodePipeline Settings"
        Parameters:
          - WorkloadName
          - Env
          - S3SourceKey
          - TemplateFileName
          - InfraDeploymentApprovalSlackNotifierStackName

Conditions:
  IsProd: !Equals [ !Ref Env, "prod" ]

Mappings:
  ValuesMap:
    poc:
      objectKeySuffix: 'poc'
    dev:
      objectKeySuffix: 'non-prod'
    it:
      objectKeySuffix: 'non-prod'
    non-prod:
      objectKeySuffix: 'non-prod'
    prod:
      objectKeySuffix: 'prod'

Resources:

  vcisCloudFormationManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'ssm:getParameters'

              - 'lambda:InvokeFunction'

              - 'cloudformation:DescribeStacks'
              - 'cloudformation:CreateStack'
              - 'cloudformation:DeleteStack'
              - 'cloudformation:UpdateStack'
              - 'cloudformation:DescribeChangeSet'
              - 'cloudformation:CreateChangeSet'
              - 'cloudformation:DeleteChangeSet'
              - 'cloudformation:ExecuteChangeSet'
              - 'cloudformation:SetStackPolicy'

              - 'ec2:createTags'
              - 'ec2:DescribeKeyPairs'

              - 'ec2:DescribeVpcs'
              - 'ec2:DescribeRegions'
              - 'ec2:CreateVpc'
              - 'ec2:DeleteVpc'
              - 'ec2:ModifyVpcAttribute'

              - 'ec2:DescribeInternetGateways'
              - 'ec2:CreateInternetGateway'
              - 'ec2:DeleteInternetGateway'
              - 'ec2:AttachInternetGateway'
              - 'ec2:DetachInternetGateway'

              - 'ec2:DescribeRouteTables'
              - 'ec2:CreateRouteTable'
              - 'ec2:DeleteRouteTable'
              - 'ec2:AssociateRouteTable'
              - 'ec2:DisassociateRouteTable'

              - 'ec2:CreateRoute'
              - 'ec2:DeleteRoute'

              - 'ec2:DescribeAvailabilityZones'
              - 'ec2:DescribeAccountAttributes'

              - 'ec2:DescribeSubnets'
              - 'ec2:CreateSubnet'
              - 'ec2:DeleteSubnet'
              - 'ec2:ModifySubnetAttribute'

              - 'ec2:DescribeSecurityGroups'
              - 'ec2:CreateSecurityGroup'
              - 'ec2:DeleteSecurityGroup'

              - 'ec2:AuthorizeSecurityGroupIngress'
              - 'ec2:AuthorizeSecurityGroupEgress'
              - 'ec2:RevokeSecurityGroupEgress'

              - 'ec2:describeAddresses'
              - 'ec2:allocateAddress'
              - 'ec2:releaseAddress'
              - 'ec2:associateAddress'
              - 'ec2:disassociateAddress'

              - 'ec2:DescribeInstances'
              - 'ec2:RunInstances'
              - 'ec2:TerminateInstances'

              - 'ec2:DescribeNatGateways'
              - 'ec2:CreateNatGateway'
              - 'ec2:DeleteNatGateway'
              - 'ec2:RevokeSecurityGroupIngress'

              - 'ecr:DescribeRepositories'
              - 'ecr:CreateRepository'
              - 'ecr:DeleteRepository'

              - 'codebuild:CreateProject'

              - 'iam:*'
              - 'kms:*'

              - 'route53:CreateHostedZone'
              - 'route53:DeleteHostedZone'
              - 'route53:GetChange'
              - 'route53:AssociateVPCWithHostedZone'
              - 'route53:CreateVPCAssociationAuthorization'
              - 'route53:DeleteVPCAssociationAuthorization'
              - 'route53:DisassociateVPCFromHostedZone'
              - 'route53:GetHostedZone'
              - 'route53:GetHostedZoneCount'
              - 'route53:ListHostedZones'
              - 'route53:ListHostedZonesByName'
              - 'route53:UpdateHostedZoneComment'
              - 'route53:ChangeResourceRecordSets'
              - 'route53:ListResourceRecordSets'
              - 'route53:ListQueryLoggingConfigs'
              
              - 'ssm:PutParameter'
              - 'ssm:AddTagsToResource'
              - 'ssm:DeleteParameter '
            Effect: Allow
            Resource: '*'
        Version: "2012-10-17"

  CfnWorkloadStackEraser:
    Type: 'Custom::CfnStackEraser'
    Version: '1.0'
    Properties:
      ServiceToken:
        Fn::ImportValue: !Sub "${CfnStackEraserStackName}-CfnStackEraserFunctionArn"
      StackName: !Sub '${WorkloadName}-${Env}'
      RoleArn:
        Fn::ImportValue: !Sub "${CfnStackEraserStackName}-CfnStackEraserExecutionRoleArn"

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
      - CfnWorkloadStackEraser
    Properties:
      ArtifactStore:
        Location:
          Fn::ImportValue: !Sub "${WorkLoadAccountLevelInputParamsStackName}-ArtifactBucket"
        Type: S3
      DisableInboundStageTransitions: []
      RoleArn: !GetAtt [PipelineRole, Arn]
      Stages:
        - Name: S3Source
          Actions:
            - Name: TemplateSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                PollForSourceChanges: false
                S3Bucket:
                  Fn::ImportValue: !Sub "${WorkLoadAccountLevelInputParamsStackName}-SourceBucket"
                S3ObjectKey: !Join
                  - '-'
                  - - !Ref S3SourceKey
                    - !FindInMap [ValuesMap, !Ref Env, objectKeySuffix]
              OutputArtifacts:
                - Name: TemplateSource
              RunOrder: 1
        - Name: UpdateStage
          Actions:
            - Name: CreateStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Sub "${WorkloadName}-${Env}-temp"
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                TemplateConfiguration: !Sub "TemplateSource::${ConfigPath}/${WorkloadName}-${Env}-update-config.json"
                TemplatePath: !Sub "TemplateSource::${TemplateFileName}"
              RunOrder: 1
            - Name: DeleteUpdatedStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: DELETE_ONLY
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Sub "${WorkloadName}-${Env}-temp"
              RunOrder: 3

        - Name: DeployStage
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Sub "${WorkloadName}-${Env}"
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                ChangeSetName: !Sub '${WorkloadName}-${Env}-change-set'
                TemplateConfiguration: !Sub "TemplateSource::${ConfigPath}/${WorkloadName}-${Env}-config.json"
                TemplatePath: !Sub "TemplateSource::${TemplateFileName}"
              RunOrder: 1
            - !If
              - IsProd
              - Name: ApproveChangeSet
                ActionTypeId:
                  Category: Approval
                  Owner: AWS
                  Provider: Manual
                  Version: '1'
                Configuration:
                  NotificationArn:
                    Fn::ImportValue: !Sub "${InfraDeploymentApprovalSlackNotifierStackName}-SNSTopicArn"
                  CustomData: !Sub 'A new change set was created for the ${WorkloadName}-${Env} stack. Do you want to implement the changes?'
                RunOrder: 2
              - !Ref AWS::NoValue
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Sub '${WorkloadName}-${Env}-change-set'
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Sub "${WorkloadName}-${Env}"
              RunOrder: 3

  CFNRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [cloudformation.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'codebuild:CreateProject'
                Effect: Allow
                Resource: '*'
      ManagedPolicyArns:
        - !Ref vcisCloudFormationManagedPolicy
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSServiceCatalogAdminFullAccess

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSNSFullAccess'
        - 'arn:aws:iam::aws:policy/IAMFullAccess'
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'ssm:getParameters'
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:CreateChangeSet'
                  - 'cloudformation:ExecuteChangeSet'
                  - 'cloudformation:DeleteChangeSet'
                  - 'cloudformation:DescribeChangeSet'
                  - 'cloudformation:SetStackPolicy'
                Effect: Allow
                Resource: '*'
              - Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Put*
                Effect: Allow
                Resource:
                  - !Join
                    - ""
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub "${WorkLoadAccountLevelInputParamsStackName}-ArtifactBucket"
                  - !Join
                    - ""
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub "${WorkLoadAccountLevelInputParamsStackName}-ArtifactBucket"
                      - '/*'
              - Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Effect: Allow
                Resource: '*'
              - Action:
                  - s3:Get*
                  - s3:List*
                Effect: Allow
                Resource:
                  - !Join
                    - ""
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub "${WorkLoadAccountLevelInputParamsStackName}-SourceBucket"
                  - !Join
                    - ""
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub "${WorkLoadAccountLevelInputParamsStackName}-SourceBucket"
                      - '/*'
              - Action: "codebuild:*"
                Effect: Allow
                Resource: "*"

  AmazonCloudWatchEventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: cwe-pipeline-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref Pipeline ] ]


  AmazonCloudWatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventSource:
            - s3.amazonaws.com
          eventName:
            - CopyObject
            - PutObject
            - CompleteMultipartUpload
          requestParameters:
            bucketName:
              - Fn::ImportValue: !Sub "${WorkLoadAccountLevelInputParamsStackName}-SourceBucket"
            key:
              - !Ref S3SourceKey
      Targets:
        -
          Arn:
            !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref Pipeline ] ]
          RoleArn: !GetAtt AmazonCloudWatchEventRole.Arn
          Id: codepipeline-AppPipeline


Outputs:
  PipelineUrl:
    Description: 'Infra CI/CD CodePipeline'
    Value:  !Join ["", [!Sub 'https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/', !Ref Pipeline] ]

