AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AWS CloudFormation Template Continuous Delivery: This template
  builds an AWS CodePipeline pipeline that implements a continuous delivery release
  process for AWS CloudFormation stacks. Submit a CloudFormation source artifact
  to an Amazon S3 location before building the pipeline. The pipeline uses the
  artifact to automatically create stacks and change sets.
Transform: [VcisCommonTagsMacro]

Parameters:
  Env:
    Description: Environment in which resources should be deployed
    Type: String
    AllowedValues:
      - dev
      - it
      - prod
    ConstraintDescription: Must be a dev, it or prod.

  WorkloadName:
    Description: Infrastructure Template Stack Name to be created by this Pipeline e.g. 'vcis-app-bulk-upload-event-sources'
    Type: String

  S3SourceKey:
    Description: S3 Source Object Name triggering this Pipeline.
    Type: String
    Default: 'vcis-app-cloudformation-templates'

  TemplateFileName:
    Description: >-
      Infrastructure template file path in vcis-app-cloudformation-templates repository to be deployed.
      e.g. 'templates/features/bulk-upload/event-sources/resources.yaml'
    Type: String

  ConfigPath:
    Description: >-
      The value is the path to the CloudFormation parameter file to deploy from vcis-app-cloudformation-templates repository.
      e.g. 'templates/features/bulk-upload/event-sources/config/dev'
    Type: String

  AppAccountLevelResourcesStackName:
    Description: >-
      Stack name exporting Application Resources like Log Group. e.g. 'vcis-app-non-prod-account-level-resources' (non-prod), 'vcis-app-prod-account-level-resources' (prod)
    Type: String

  ProjectModuleTag:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Environment specific SSM Param Name for Project Module Tag
    AllowedValues:
      - /vcis/dev/infra/tags/project-module-pod
      - /vcis/dev/infra/tags/project-module-sales
      - /vcis/dev/infra/tags/project-module-multiplication
      - /vcis/dev/infra/tags/project-module-legally-saved-seeds
      - /vcis/dev/infra/tags/project-module-master-data
      - /vcis/it/infra/tags/project-module-pod
      - /vcis/it/infra/tags/project-module-sales
      - /vcis/it/infra/tags/project-module-multiplication
      - /vcis/it/infra/tags/project-module-legally-saved-seeds
      - /vcis/it/infra/tags/project-module-master-data
      - /vcis/prod/infra/tags/project-module-pod
      - /vcis/prod/infra/tags/project-module-sales
      - /vcis/prod/infra/tags/project-module-multiplication
      - /vcis/prod/infra/tags/project-module-legally-saved-seeds
      - /vcis/prod/infra/tags/project-module-master-data

  CfnStackEraserStackName:
    Type: String
    Description: 'Cfn stack eraser custom resource stack'
    Default: 'vcis-cloudformation-custom-resources'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Deployment Environment"
        Parameters:
          - Env
      - Label:
          default: "CodePipeline Settings - Infrastructure Template Deployment"
        Parameters:
          - WorkloadName
          - S3SourceKey
          - TemplateFileName
          - ConfigPath
      - Label:
          default: "Cloud Formation Stack Name exporting Application Resources"
        Parameters:
          - AppAccountLevelResourcesStackName
      - Label:
          default: "Tagging Configuration"
        Parameters:
          - ProjectModuleTag
    ParameterLabels:
      Env:
        default: "Environment"
      WorkloadName:
        default: "Infrastructure Template Stack Name"
      S3SourceKey:
        default: "Pipeline Trigger - S3 Source Object Name"
      TemplateFileName:
        default: "Infrastructure Template File Path"
      ConfigPath:
        default: "Infrastructure Template Config Path"
      AppAccountLevelResourcesStackName:
        default: "Stack name exporting Application Resources"
      ProjectModuleTag:
        default: "SSM Param Name for Project Module Tag"

Conditions:
  IsProd: !Equals [ !Ref Env, "prod" ]

Resources:

  vcisCloudFormationManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'ssm:getParameters'
              - 'ssm:PutParameter'
              - 'ssm:DeleteParameter'
              - 'ssm:AddTagsToResource'

              - 'lambda:InvokeFunction'

              - 'cloudformation:DescribeStacks'
              - 'cloudformation:CreateStack'
              - 'cloudformation:DeleteStack'
              - 'cloudformation:UpdateStack'
              - 'cloudformation:DescribeChangeSet'
              - 'cloudformation:CreateChangeSet'
              - 'cloudformation:DeleteChangeSet'
              - 'cloudformation:ExecuteChangeSet'
              - 'cloudformation:SetStackPolicy'

              - 'ec2:createTags'
              - 'ec2:DescribeKeyPairs'

              - 'ec2:DescribeVpcs'
              - 'ec2:CreateVpc'
              - 'ec2:DeleteVpc'
              - 'ec2:ModifyVpcAttribute'

              - 'ec2:DescribeInternetGateways'
              - 'ec2:CreateInternetGateway'
              - 'ec2:DeleteInternetGateway'
              - 'ec2:AttachInternetGateway'
              - 'ec2:DetachInternetGateway'

              - 'ec2:DescribeRouteTables'
              - 'ec2:CreateRouteTable'
              - 'ec2:DeleteRouteTable'
              - 'ec2:AssociateRouteTable'
              - 'ec2:DisassociateRouteTable'

              - 'ec2:CreateRoute'
              - 'ec2:DeleteRoute'

              - 'ec2:DescribeAvailabilityZones'
              - 'ec2:DescribeAccountAttributes'

              - 'ec2:DescribeSubnets'
              - 'ec2:CreateSubnet'
              - 'ec2:DeleteSubnet'
              - 'ec2:ModifySubnetAttribute'

              - 'ec2:DescribeSecurityGroups'
              - 'ec2:CreateSecurityGroup'
              - 'ec2:DeleteSecurityGroup'

              - 'ec2:AuthorizeSecurityGroupIngress'
              - 'ec2:AuthorizeSecurityGroupEgress'
              - 'ec2:RevokeSecurityGroupEgress'

              - 'ec2:describeAddresses'
              - 'ec2:allocateAddress'
              - 'ec2:releaseAddress'
              - 'ec2:associateAddress'
              - 'ec2:disassociateAddress'

              - 'ec2:DescribeInstances'
              - 'ec2:RunInstances'
              - 'ec2:TerminateInstances'

              - 'ec2:DescribeNatGateways'
              - 'ec2:CreateNatGateway'
              - 'ec2:DeleteNatGateway'

              - 'ecr:DescribeRepositories'
              - 'ecr:CreateRepository'
              - 'ecr:DeleteRepository'

              - 'codebuild:CreateProject'

              - 'iam:*'
              - 'kms:*'
              - 'sqs:*'
              - 'sns:*'

              - 'route53:GetHostedZone*'
              - 'route53:ChangeResourceRecordSets'
              - 'route53:GetChange*'
              - 'route53:ListResourceRecordSets'

              - 'cloudfront:UpdateDistribution'
            
            Effect: Allow
            Resource: '*'
        Version: "2012-10-17"

  CfnChildStackEraser:
    Type: 'Custom::CfnStackEraser'
    Version: '1.0'
    Properties:
      ServiceToken:
        Fn::ImportValue: !Sub "${CfnStackEraserStackName}-CfnStackEraserFunctionArn"
      StackName: !Sub '${WorkloadName}-${Env}'
      RoleArn:
        Fn::ImportValue: !Sub "${CfnStackEraserStackName}-CfnStackEraserExecutionRoleArn"

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
      - CfnChildStackEraser
    Properties:
      ArtifactStore:
        Location:
          Fn::ImportValue: !Sub "${AppAccountLevelResourcesStackName}-ArtifactBucket"
        Type: S3
      DisableInboundStageTransitions: []
      RoleArn: !GetAtt [PipelineRole, Arn]
      Stages:
        - Name: S3Source
          Actions:
            - Name: TemplateSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                S3Bucket:
                  Fn::ImportValue: !Sub "${AppAccountLevelResourcesStackName}-SourceBucket"
                S3ObjectKey: !Sub '${S3SourceKey}-${Env}'
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: TemplateSource
              RunOrder: 1
        - Name: UpdateStage
          Actions:
            - Name: CreateStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Sub "${WorkloadName}-${Env}-temp"
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                TemplateConfiguration: !Sub "TemplateSource::${ConfigPath}/${WorkloadName}-${Env}-update-config.json"
                TemplatePath: !Sub "TemplateSource::${TemplateFileName}"
              RunOrder: 1
            - Name: DeleteUpdatedStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: DELETE_ONLY
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Sub "${WorkloadName}-${Env}-temp"
              RunOrder: 3

        - Name: DeployStage
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Sub "${WorkloadName}-${Env}"
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                ChangeSetName: !Sub '${WorkloadName}-${Env}-change-set'
                TemplateConfiguration: !Sub "TemplateSource::${ConfigPath}/${WorkloadName}-${Env}-config.json"
                TemplatePath: !Sub "TemplateSource::${TemplateFileName}"
              RunOrder: 1
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Sub '${WorkloadName}-${Env}-change-set'
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Sub "${WorkloadName}-${Env}"
              RunOrder: 3

  CFNRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [cloudformation.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'codebuild:CreateProject'
                Effect: Allow
                Resource: '*'
      ManagedPolicyArns:
        - !Ref vcisCloudFormationManagedPolicy
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSNSFullAccess'
        - 'arn:aws:iam::aws:policy/IAMFullAccess'
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'ssm:getParameters'
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:CreateChangeSet'
                  - 'cloudformation:ExecuteChangeSet'
                  - 'cloudformation:DeleteChangeSet'
                  - 'cloudformation:DescribeChangeSet'
                  - 'cloudformation:SetStackPolicy'
                Effect: Allow
                Resource: '*'
              - Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Put*
                Effect: Allow
                Resource:
                  - !Join
                    - ""
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub "${AppAccountLevelResourcesStackName}-ArtifactBucket"
                  - !Join
                    - ""
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub "${AppAccountLevelResourcesStackName}-ArtifactBucket"
                      - '/*'
              - Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Effect: Allow
                Resource: '*'
              - Action:
                  - s3:Get*
                  - s3:List*
                Effect: Allow
                Resource:
                  - !Join
                    - ""
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub "${AppAccountLevelResourcesStackName}-SourceBucket"
                  - !Join
                    - ""
                    - - 'arn:aws:s3:::'
                      - Fn::ImportValue: !Sub "${AppAccountLevelResourcesStackName}-SourceBucket"
                      - '/*'
              - Action: "codebuild:*"
                Effect: Allow
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:DeleteRolePermissionsBoundary
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/vcis*'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: 
                  - !Sub arn:aws:sns:us-east-1:${AWS::AccountId}:vcis-*                

  AmazonCloudWatchEventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: cwe-pipeline-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref Pipeline ] ]


  AmazonCloudWatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventSource:
            - s3.amazonaws.com
          eventName:
            - CopyObject
            - PutObject
            - CompleteMultipartUpload
          requestParameters:
            bucketName:
              - Fn::ImportValue: !Sub "${AppAccountLevelResourcesStackName}-SourceBucket"
            key:
              - !Sub '${S3SourceKey}-${Env}'
      Targets:
        -
          Arn:
            !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref Pipeline ] ]
          RoleArn: !GetAtt AmazonCloudWatchEventRole.Arn
          Id: codepipeline-AppPipeline


Outputs:
  PipelineUrl:
    Description: 'Infra CI/CD CodePipeline'
    Value:  !Join ["", [!Sub 'https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/', !Ref Pipeline] ]
