version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt-get update -y
      - node --version
      - npm config set registry https://registry.npmjs.org/
      - npm install --unsafe-perm
  build:
    commands:
      - aws cloudformation package --template sam.yaml --s3-bucket ${BUILD_OUTPUT_BUCKET} --output-template sam-output.yaml
artifacts:
  files:
    - sam-output.yaml
    - config/cfn/${ENV}/sam-config.json
  discard-paths: yes
  type: zip
  name: vcis-pipeline-manager-service-${ENV}
