AWSTemplateFormatVersion: '2010-09-09'
Description: 'VCIS Api gateway Metrics'

Transform: [VcisCommonTagsMacro]

Parameters:
  ApiName:
    Type: String
    Description: The api name
  Env:
    Type: String
    AllowedValues:
      - dev
      - it
      - prod
      - poc
    ConstraintDescription: Environment values must be dev, it, prod or poc
  ProjectModuleTag:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Project Module Tag Value
  4XXErrorThreshold:
    Type: Number
    Description: The value to compare with the specified statistic
    MinValue: 0
  5XXErrorThreshold:
    Type: Number
    Description: The value to compare with the specified statistic
    MinValue: 0
  LatencyThreshold:
    Type: Number
    Description: The value to compare with the specified statistic
    MinValue: 0
  Period:
    Type: Number
    Description: The period, in seconds, over which the statistic is applied
    Default: 300
  LambdaSubscription:
    Type: String
    Description: An AWS Lambda function that can receive notifications from Amazon SNS

Resources:
  ApiNameSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ApiName}-${Env}-AlarmNotificationTopic'
  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref LambdaSubscription
      Protocol: lambda
      TopicArn:
        Ref: ApiNameSNSTopic

  4XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - Ref: ApiNameSNSTopic
      AlarmDescription: !Sub '${ApiName} - The number of client-side errors captured in a given period'
      AlarmName: !Sub '${ApiName}-${Env}-4XXError'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: '4XXError'
      Namespace: 'AWS/ApiGateway'
      Period: !Ref Period
      Statistic: Sum
      Threshold: !Ref 4XXErrorThreshold
      Dimensions:
        [
         {
            "Name": "ApiName",
            "Value": !Ref ApiName
         }
        ]

  5XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - Ref: ApiNameSNSTopic
      AlarmDescription: !Sub '${ApiName} - The number of server-side errors captured in a given period'
      AlarmName: !Sub '${ApiName}-${Env}-5XXError'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: '5XXError'
      Namespace: 'AWS/ApiGateway'
      Period: !Ref Period
      Statistic: Sum
      Threshold: !Ref 5XXErrorThreshold
      Dimensions:
        [
         {
            "Name": "ApiName",
            "Value": !Ref ApiName
         }
        ]

  LatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - Ref: ApiNameSNSTopic
      AlarmDescription: !Sub '${ApiName} - The time between when API Gateway receives a request from a client and when it returns a response to the client. The latency includes the integration latency and other API Gateway overhead (Millisecond)'
      AlarmName: !Sub '${ApiName}-${Env}-Latency'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: 'Latency'
      Namespace: 'AWS/ApiGateway'
      Period: !Ref Period
      Statistic: Average
      Threshold: !Ref LatencyThreshold
      Dimensions:
        [
         {
            "Name": "ApiName",
            "Value": !Ref ApiName
         }
        ]
