AWSTemplateFormatVersion: "2010-09-09"

Description: >
  AWS CloudFormation Template For Service Catalog Product - Application Infrastructure CI-CD Pipeline

Transform: [VcisCommonTagsMacro]

Parameters:
  Env:
    Description: 'Environment in which resources should be deployed'
    Type: String
    AllowedValues:
      - non-prod
      - prod
    ConstraintDescription: Must be either non-prod or prod

  ProjectModuleTag:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Project Module Tag Value

  AppInfraCiCdPipelineProductName:
    Description: Service Catalog Product Name for Application Infrastructure CI CD Pipeline
    Type: String
    Default: 'app-infra-ci-cd-pipeline'

  AppInfraCiCdPipelineProductDescription:
    Description: Service Catalog Product Description for Application Infrastructure CI CD Pipeline
    Type: String
    Default: 'CI-CD Pipeline for Application Infrastructure Resources Deployment'

  AccountLevelResourcesStackName:
    Description: >-
      Stack name exporting Account Level Resources like Service Catalog Product Source Bucket.
    Type: String

Resources:
  AppInfraCiCdPipelineProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: !Ref AppInfraCiCdPipelineProductName
      Description: !Ref AppInfraCiCdPipelineProductDescription
      Owner: 'VCIS Cloud Admin'
      ProvisioningArtifactParameters:
        - Name: 1.0.0
          Description: 'Initial Version'
          Info:
            "LoadTemplateFromURL":
              !Join
              - ''
              - - "https://"
                - Fn::ImportValue: !Sub "${AccountLevelResourcesStackName}-ServiceCatalogProductsSourceBucket"
                - ".s3.amazonaws.com/app-infra-ci-cd-pipeline/1.0.0/app-infra-ci-cd-pipeline.yaml"
        - Name: 1.0.1
          Description: 'Support for child stack deletion when pipeline is begin deleted'
          Info:
            "LoadTemplateFromURL":
              !Join
              - ''
              - - "https://"
                - Fn::ImportValue: !Sub "${AccountLevelResourcesStackName}-ServiceCatalogProductsSourceBucket"
                - ".s3.amazonaws.com/app-infra-ci-cd-pipeline/1.0.1/app-infra-ci-cd-pipeline.yaml"
        - Name: 1.0.2
          Description: 'Remove PermissionsBoundary'
          Info:
            "LoadTemplateFromURL":
              !Join
              - ''
              - - "https://"
                - Fn::ImportValue: !Sub "${AccountLevelResourcesStackName}-ServiceCatalogProductsSourceBucket"
                - ".s3.amazonaws.com/app-infra-ci-cd-pipeline/1.0.2/app-infra-ci-cd-pipeline.yaml"
        - Name: 1.0.3
          Description: 'Added needed permissions to create custom domain for APIs'
          Info:
            "LoadTemplateFromURL":
              !Join
              - ''
              - - "https://"
                - Fn::ImportValue: !Sub "${AccountLevelResourcesStackName}-ServiceCatalogProductsSourceBucket"
                - ".s3.amazonaws.com/app-infra-ci-cd-pipeline/1.0.3/app-infra-ci-cd-pipeline.yaml"
        - Name: 1.0.4
          Description: 'Added needed permissions for allowing Approval Tool send SNS messages'
          Info:
            "LoadTemplateFromURL":
              !Join
              - ''
              - - "https://"
                - Fn::ImportValue: !Sub "${AccountLevelResourcesStackName}-ServiceCatalogProductsSourceBucket"
                - ".s3.amazonaws.com/app-infra-ci-cd-pipeline/1.0.4/app-infra-ci-cd-pipeline.yaml"
        - Name: 1.0.5
          Description: 'Replaced Cfn stack eraser default value'
          Info:
            "LoadTemplateFromURL":
              !Join
              - ''
              - - "https://"
                - Fn::ImportValue: !Sub "${AccountLevelResourcesStackName}-ServiceCatalogProductsSourceBucket"
                - ".s3.amazonaws.com/app-infra-ci-cd-pipeline/1.0.5/app-infra-ci-cd-pipeline.yaml"
        - Name: 1.0.6
          Description: 'Removed approval step for infra stuff'
          Info:
            "LoadTemplateFromURL":
              !Join
              - ''
              - - "https://"
                - Fn::ImportValue: !Sub "${AccountLevelResourcesStackName}-ServiceCatalogProductsSourceBucket"
                - ".s3.amazonaws.com/app-infra-ci-cd-pipeline/1.0.6/app-infra-ci-cd-pipeline.yaml"
      SupportDescription: 'Please contact VCIS Cloud Admins for any assistance.'
      SupportUrl: 'https://velocity.ag/profile/groups/VCISADMINROLESSO/members'

Outputs:
  AppInfraCiCdPipelineProductId:
    Description: 'Application Infrastructure CI-CD Pipeline - Service Catalog Product ID'
    Value: !Ref AppInfraCiCdPipelineProduct
    Export:
      Name: !Sub '${AWS::StackName}-AppInfraCiCdPipelineProductId'
