AWSTemplateFormatVersion: '2010-09-09'
Description: VCIS API Gateway

Transform: [VcisCommonTagsMacro]

Parameters:
  Env:
    Type: String
    Description: Environment in which resources should be deployed
    AllowedValues:
      - poc
      - dev
      - it
      - prod
    ConstraintDescription: Must be either poc, dev, it or prod

  ProjectModuleTag:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Project Module Tag SSM Param Name. Default is '/vcis/{Env}/infra/tags/project-module-value-capture-industry-system'

  RestApiName:
    Type: String
    Description: 'The API Name (eg: vcis-pod-credit-exemption-balance)'

  RestApiDescription:
    Type: String
    Description: Rest API Description

  StageName:
    Type: String
    Description: The name of the API Stage. Default is 'release' stage
    Default: 'release'

  RestApiCustomDomainName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Rest API Custom Domain Name. Default value is 'api.pod-np.its-plus.com' (NonProd) and 'api.pod.its-plus.com' (Prod)

  LambdaAuthorizerStackName:
    Type: String
    Description: Stack that exports Lambda Authorizer ARN.

  MinimumCompressionSize:
    Type: Number
    Default: 0
    Description: 'Compression or decompression is not applied on the payload if the payload size is smaller than this value. Setting it to zero allows compression for any payload size.'

  CustomTags:
    Type: String
    Description: "Custom tags to apply on template"
    Default: ''

Mappings:
  EnvStageVarMapping:
    poc:
      EnvStageVar: 'DEV'
    dev:
      EnvStageVar: 'DEV'
    it:
      EnvStageVar: 'TEST'
    prod:
      EnvStageVar: 'PROD'

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${RestApiName}-${Env}'
      Description: !Ref RestApiDescription
      ApiKeySourceType: HEADER
      MinimumCompressionSize: !Ref MinimumCompressionSize
      EndpointConfiguration:
        Types:
          - EDGE

    ## Lambda Authorizer
  ApiGatewayLambdaAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    DependsOn: RestApi
    Properties:
      Name: !Sub 'vcis-pod-ping-authorizer-${Env}'
      Type: 'REQUEST'
      AuthorizerResultTtlInSeconds: 0
      AuthorizerUri: !Join
        - ''
        - - 'arn:aws:apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - Fn::ImportValue: !Sub "${LambdaAuthorizerStackName}-PodPingAuthorizer"
          - '/invocations'
      IdentitySource: 'method.request.header.Authorization'
      RestApiId: !Ref RestApi

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
    - BulkPath
    - BulkCOMMERCIALHIERARCHYPath
    - BulkCOMMERCIALHIERARCHYbulkIdPath
    - BulkCOMMERCIALHIERARCHYbulkIderrorsPath
    - BulkCOMMERCIALHIERARCHYEXCEPTIONPath
    - BulkCOMMERCIALHIERARCHYEXCEPTIONbulkPath
    - BulkCOMMERCIALHIERARCHYEXCEPTIONbulkerrorsPath
    - BulkMANUALGENERATIONPath
    - BulkMANUALGENERATIONbulkIdPath
    - BulkMANUALGENERATIONbulkIderrorsPath
    - BulkCOMMERCIALHIERARCHYOptionsMethod
    - BulkCOMMERCIALHIERARCHYbulkIderrorsOptionsMethod
    - BulkCOMMERCIALHIERARCHYEXCEPTIONOptionsMethod
    - BulkCOMMERCIALHIERARCHYEXCEPTIONbulkerrorsOptionsMethod
    - BulkMANUALGENERATIONOptionsMethod
    - BulkMANUALGENERATIONbulkIderrorsOptionsMethod
    Properties:
      Description: API Deployment
      RestApiId: !Ref RestApi

  Stage:
    Type: AWS::ApiGateway::Stage
    DependsOn: Deployment
    Properties:
      RestApiId: !Ref RestApi
      DeploymentId: !Ref Deployment
      StageName: !Ref StageName
      Variables:
        environment: !FindInMap [EnvStageVarMapping, !Ref Env, EnvStageVar]

  ApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: Stage
    Properties:
      DomainName: !Ref RestApiCustomDomainName
      BasePath: !Sub '${RestApiName}-${Env}'
      RestApiId: !Ref RestApi
      Stage: !Ref Stage

  BulkPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: "bulk"
      RestApiId: !Ref RestApi

  BulkCOMMERCIALHIERARCHYPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref BulkPath
      PathPart: "COMMERCIAL_HIERARCHY"
      RestApiId: !Ref RestApi

  BulkCOMMERCIALHIERARCHYOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref BulkCOMMERCIALHIERARCHYPath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  BulkCOMMERCIALHIERARCHYbulkIdPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref BulkCOMMERCIALHIERARCHYPath
      PathPart: "{bulkId}"
      RestApiId: !Ref RestApi

  BulkCOMMERCIALHIERARCHYbulkIderrorsPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref BulkCOMMERCIALHIERARCHYbulkIdPath
      PathPart: "errors"
      RestApiId: !Ref RestApi

  BulkCOMMERCIALHIERARCHYbulkIderrorsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref BulkCOMMERCIALHIERARCHYbulkIderrorsPath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  BulkCOMMERCIALHIERARCHYEXCEPTIONPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref BulkPath
      PathPart: "COMMERCIAL_HIERARCHY_EXCEPTION"
      RestApiId: !Ref RestApi

  BulkCOMMERCIALHIERARCHYEXCEPTIONOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref BulkCOMMERCIALHIERARCHYEXCEPTIONPath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  BulkCOMMERCIALHIERARCHYEXCEPTIONbulkPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref BulkCOMMERCIALHIERARCHYEXCEPTIONPath
      PathPart: "{bulk}"
      RestApiId: !Ref RestApi

  BulkCOMMERCIALHIERARCHYEXCEPTIONbulkerrorsPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref BulkCOMMERCIALHIERARCHYEXCEPTIONbulkPath
      PathPart: "errors"
      RestApiId: !Ref RestApi

  BulkCOMMERCIALHIERARCHYEXCEPTIONbulkerrorsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref BulkCOMMERCIALHIERARCHYEXCEPTIONbulkerrorsPath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  BulkMANUALGENERATIONPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref BulkPath
      PathPart: "MANUAL_GENERATION"
      RestApiId: !Ref RestApi

  BulkMANUALGENERATIONOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref BulkMANUALGENERATIONPath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
  BulkMANUALGENERATIONbulkIdPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref BulkMANUALGENERATIONPath
      PathPart: "{bulkId}"
      RestApiId: !Ref RestApi

  BulkMANUALGENERATIONbulkIderrorsPath:
    Type: AWS::ApiGateway::Resource
    DependsOn: ApiGatewayLambdaAuthorizer
    Properties:
      ParentId: !Ref BulkMANUALGENERATIONbulkIdPath
      PathPart: "errors"
      RestApiId: !Ref RestApi

  BulkMANUALGENERATIONbulkIderrorsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      RestApiId: !Ref RestApi
      ResourceId: !Ref BulkMANUALGENERATIONbulkIderrorsPath
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false

Outputs:
  Endpoint:
    Description: Rest Api Endpoint URL
    Value: !Sub 'https://${RestApiName}-${Env}.execute-api.${AWS::Region}.amazonaws.com'

  RestApiGatewayId:
    Description: ApiGatewayId
    Value: !Ref RestApi
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayId'

  RootResourceId:
    Description: RootResourceId
    Value: !GetAtt RestApi.RootResourceId
    Export:
      Name: !Sub '${AWS::StackName}-RootResourceId'

  LambdaAuthorizerId:
    Description: LambdaAuthorizerId
    Value: !Ref ApiGatewayLambdaAuthorizer
    Export:
      Name: !Sub '${AWS::StackName}-LambdaAuthorizerId'

  BulkPath:
    Value: !Ref BulkPath
    Export:
      Name: !Sub '${AWS::StackName}-BulkPath'
  BulkCOMMERCIALHIERARCHYPath:
    Value: !Ref BulkCOMMERCIALHIERARCHYPath
    Export:
      Name: !Sub '${AWS::StackName}-BulkCOMMERCIALHIERARCHYPath'
  BulkCOMMERCIALHIERARCHYbulkIdPath:
    Value: !Ref BulkCOMMERCIALHIERARCHYbulkIdPath
    Export:
      Name: !Sub '${AWS::StackName}-BulkCOMMERCIALHIERARCHYbulkIdPath'
  BulkCOMMERCIALHIERARCHYbulkIderrorsPath:
    Value: !Ref BulkCOMMERCIALHIERARCHYbulkIderrorsPath
    Export:
      Name: !Sub '${AWS::StackName}-BulkCOMMERCIALHIERARCHYbulkIderrorsPath'
  BulkCOMMERCIALHIERARCHYEXCEPTIONPath:
    Value: !Ref BulkCOMMERCIALHIERARCHYEXCEPTIONPath
    Export:
      Name: !Sub '${AWS::StackName}-BulkCOMMERCIALHIERARCHYEXCEPTIONPath'
  BulkCOMMERCIALHIERARCHYEXCEPTIONbulkPath:
    Value: !Ref BulkCOMMERCIALHIERARCHYEXCEPTIONbulkPath
    Export:
      Name: !Sub '${AWS::StackName}-BulkCOMMERCIALHIERARCHYEXCEPTIONbulkPath'
  BulkCOMMERCIALHIERARCHYEXCEPTIONbulkerrorsPath:
    Value: !Ref BulkCOMMERCIALHIERARCHYEXCEPTIONbulkerrorsPath
    Export:
      Name: !Sub '${AWS::StackName}-BulkCOMMERCIALHIERARCHYEXCEPTIONbulkerrorsPath'
  BulkMANUALGENERATIONPath:
    Value: !Ref BulkMANUALGENERATIONPath
    Export:
      Name: !Sub '${AWS::StackName}-BulkMANUALGENERATIONPath'
  BulkMANUALGENERATIONbulkIdPath:
    Value: !Ref BulkMANUALGENERATIONbulkIdPath
    Export:
      Name: !Sub '${AWS::StackName}-BulkMANUALGENERATIONbulkIdPath'
  BulkMANUALGENERATIONbulkIderrorsPath:
    Value: !Ref BulkMANUALGENERATIONbulkIderrorsPath
    Export:
      Name: !Sub '${AWS::StackName}-BulkMANUALGENERATIONbulkIderrorsPath'
